FROM centos:7.9

RUN yum -y update && yum -y upgrade \
    && yum install -y centos-release-scl \
    && yum install -y devtoolset-11-gcc* \
    && ln -sf /opt/rh/devtoolset-11/root/bin/gcc /usr/bin/gcc \
    && ln -sf /opt/rh/devtoolset-11/root/bin/g++ /usr/bin/g++ \
    && ln -sf /opt/rh/devtoolset-11/root/bin/c++ /usr/bin/c++ \
    && ln -sf /opt/rh/devtoolset-11/root/bin/cpp /usr/bin/cpp \
    && ln -sf /opt/rh/devtoolset-11/root/bin/cc /usr/bin/cc \
    && yum install -y epel-release \
    && yum install -y cmake3 make mysql-devel git openssl-devel gflags-devel leveldb-devel which \
        python3 libnl3-devel libudev-devel valgrind-devel pandoc python3-Cython python-docutils python3-docutils python3-devel \
    && yum clean all \
    && ln -sf /usr/bin/cmake3 /usr/bin/cmake

# build and install spdlog
RUN git clone https://github.com/gabime/spdlog.git -b v1.12.0 \
    && cd spdlog && mkdir build && cd build \
    && cmake .. && make -j && make install \
    && cd ../../ && rm -rf spdlog

# build and install protobuf, due to yum only installs proto2
RUN git clone https://github.com/protocolbuffers/protobuf.git -b v21.10 \  
    && cd protobuf && git submodule update --init --recursive \
    && mkdir build && cd build && cmake .. && make -j && make install \
    && cd ../.. && rm -rf protobuf

# build install brpc
RUN git clone https://github.com/apache/brpc.git && cd brpc \
    && sh config_brpc.sh --headers="/usr/include /usr/local/include" --libs="/usr/lib64 /usr/local/lib64" \
    && make -j && make install \
    && cd .. && rm -rf brpc

# build rdma userspace library
RUN git clone https://github.com/linux-rdma/rdma-core.git \
    && cd rdma-core && cmake . && make -j && make install \
    && cd .. && rm -rf rdma-core

# docker build -t registry.cn-hangzhou.aliyuncs.com/sensecore-transom/tce-build:1.0-centos . -f dockerfile/centos/Dockerfile.build
